### ISSUE TITLE
Failed to open server from jack_control even though jack and jackdbus are running

### ISSUE THREAD

**Issue by kiwi-ed** [jackaudio/jack1#101]
Hi,

Platform: ARM - headless server using Jack2 
Config: ./waf configure  cross_compiling=yes --dbus --classic
Running:  jackd -R -d alsa -r44100 and jackdbus auto

For whatever reason jack_control cannot communicate with jackd. Ultimately I'm aiming to us the sm (switch-master) option but it always reports the server is stopped. Trying to start the server via jack-control results in 'DBus exception: org.jackaudio.Error.Generic: Failed to open server'. If I kill "jackd" then I get the DBus error 'DBus exception: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying' so there seems to be some coms between jackd and jack_control. 
The jackd server is operating correctly in an audio/connection sense it's just the issue between it and jack_control. 

My DBus conf is:
<busconfig>
  
  <policy user="root">
    <allow own="org.jackaudio.service"/>
  </policy>
  
  <policy context="default">
    <allow send_destination="org.jackaudio.service"/>
    <allow receive_sender="org.jackaudio.service"/>
  </policy>
</busconfig>

And using  export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket

Thanks.

**Comment by falkTX** [comment]
you are reporting this issue in jack1 repo. jack1 does not provide dbus support

in the case of jack2, jackd does not provide dbus support.
in order to use switch master and switch commands, you need to use jack_control to start jack, and completely ignore jackd as if it does not even exist.
(safest choice is to build without --classic)
