### ISSUE TITLE
Unable to compile from source

### ISSUE THREAD

**Issue by uberhacker** [jackaudio/jack1#106]
This seems to be consistent with all releases including HEAD.

```
$ ./autogen.sh 
configure.ac:149: installing 'config/compile'
configure.ac:66: installing 'config/config.guess'
configure.ac:66: installing 'config/config.sub'
configure.ac:136: installing 'config/install-sh'
configure.ac:136: installing 'config/missing'
configure.ac:965: error: required file 'example-clients/Makefile.in' not found
configure.ac:965: error: required file 'tools/Makefile.in' not found
configure.ac:965: error: required file 'tools/zalsa/Makefile.in' not found
drivers/alsa/Makefile.am: installing 'config/depcomp'
automake --add-missing --foreign failed, exiting...
```
This results in no configure script.  What is the recommended way to compile from source?

**Comment by falkTX** [comment]
When cloning from git, make sure to use --recursive option or init submodules after cloning.

**Comment by uberhacker** [comment]
@falkTX: Thank you for the quick reply.  Yes, I noticed the instructions were located at https://jackaudio.org/downloads/.  Would it make sense to include a `How to build from source` section in the README.md of this project?

**Comment by falkTX** [comment]
pull requests welcome :)

but working with git submodule is something that should be standard by this point tbh...
