### ISSUE TITLE
Installing in catalina but invisible, can't uninstall.

### ISSUE THREAD

**Issue by ben-milkshake** [jackaudio/jack1#107]
Hi guys.
I installed the last release.
the installer said went ok.
but no jack folder in the application directory, nowhere any files from the tool.
when I go to OBS, it is visible in the sound devices list, but cannot be used.

I looked up to uninstall with mac remover tool, it is not listed either !
so I try with another tool and nothing works, might due to a conflict ! 

please help.

have a good day

**Comment by falkTX** [comment]
See https://github.com/jackaudio/jack2/issues/689

jack is a system service, not an application.
an uninstaller will be added at a later point, for now, see /usr/local/share/jack2/jack2-osx-files.txt for the list of files.
they are listed on the 1st page of the installer too, not sure if you read that.

**Comment by ben-milkshake** [comment]
Thank you for your response.
there's no such file (jack2-osx-files) in my entire system ! 
yes the 1st page of jack2-osx-1.9.16 installer listed them, Cannot find any. 
nothing with Jack besides the zip and installer. 
nevertheless it is listed in OBS .

Thank you for your help.
best

**Comment by falkTX** [comment]
Then you must have installed jack some other way, which is unsupported.

**Comment by ben-milkshake** [comment]
HI, I did not  ! I do not even know how to do.
I did run the installation again now, no file created even if installer is saying correct installation !
can't find jack2-osx-files

any other idea? 
thx

**Comment by ben-milkshake** [comment]
Help please :)

**Comment by falkTX** [comment]
if you installed it and it says installation complete, I am not sure what else to tell you...

from where did you install it?
anything outside of https://jackaudio.org/downloads/ is unsupported
