### ISSUE TITLE
Jack prebuilt binary won't install on OSX Yosemite 10.10

### ISSUE THREAD

**Issue by geelen** [jackaudio/jack1#11]
Getting a spurious error message: 

![image](https://cloud.githubusercontent.com/assets/23264/3816972/719ed5bc-1cd3-11e4-90b4-a7195a8095af.png)

Guessing someone's doing a version check and '10.10' is failing.

**Comment by joshdekock** [comment]
Can this be closed?

**Comment by Qix-** [comment]
This should be closed. :)

**Comment by falkTX** [comment]
Closing after 6 years :)
