### ISSUE TITLE
jackd gets blocked when a client gets killed

### ISSUE THREAD

**Issue by abique** [jackaudio/jack1#15]
Hi,

While using clap-jack-host, I often just kill the client with Ctrl+C in the console and pretty often qjackctl stops refreshing and it seems that jackd gets locked.

Thanks,
Alex.

**Comment by abique** [comment]
Here is clap-jack-host: https://github.com/free-audio/clap/blob/master/tools/clap-jack-host/clap-jack-host.c

**Comment by falkTX** [comment]
you should capture that ctrl+c and shortly afterwards deactivate and close your client.
although jack should preferably handle this case better, killing the process on purpose is not nice.

**Comment by pauldavisthefirst** [comment]
I routinely ctrl-c clients while using JACK1. The server will hang for the client timeout period, and then resumes without any problems.

**Comment by joshdekock** [comment]
Can be closed, as it is the expected behaviour?

**Comment by MrMormon** [comment]
Seconded unless someone has a proposal to "handle this case better".

**Comment by falkTX** [comment]
Closing this issue then, as suggested.
