### ISSUE TITLE
How do you remove jack from system?

### ISSUE THREAD

**Issue by lacostenycoder** [jackaudio/jack1#30]
Can't find uninstall script or instructions on website or repo.

**Comment by pauldavisthefirst** [comment]
This is a bit an ill-formed question. You've provided no information on how you installed JACK.

If you installed it from a Linux repository using some platform specific software management tool, then you use the same tool to uninstall it. If you installed it from source using "sudo make install", then you uninstall it with "sudo make uninstall" from a source tree. 

This is all 100% standard for almost all software on Linux.

**Comment by lacostenycoder** [comment]
I should have mentioned I installed this on OSX quite a long time ago and don't remember how it was installed.  However I found there was an uninstall script in in the /Applications/Jack/ folder.  Problem solved.  Thanks.
