### ISSUE TITLE
Can't build jack1 with --prefix

### ISSUE THREAD

**Issue by unclechu** [jackaudio/jack1#5]
I have installed JACK2 already, but I need to compile JACK1 and I can't do it.

$ ./configure --prefix=/opt/jack1-git
configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
checking existing, conflicting JACK installs... 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
You appear to have at least one existing installation of JACK.

Complete or partial JACK installs exist in: /usr/lib

Installing this version will leave at least one of these
existing installations installed and this will probably break
JACK on your machine. 

Before building, you should first remove the existing JACK
installation(s). 

Alternatively use ./configure --prefix=... to force overwriting
the existing install.

WARNING: ON ANY DEBIAN-DERIVED DISTRIBUTION (Debian, Ubuntu etc)
CHANGING THE INSTALLATION PREFIX WILL NOT PRODUCE A WORKING JACK
INSTALL. Please contact the distribution packager for JACK and
ask them to fix their packaging.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by joshdekock** [comment]
Can this be closed?

**Comment by MrMormon** [comment]
This should absolutely be closed. This is nothing new.

**Comment by adiknoth** [comment]
There's an override flag now, this is indeed obsolete.
