### ISSUE TITLE
Download Link

### ISSUE THREAD

**Issue by okumedia** [jackaudio/jack1#64]
The download link for windows users at http://jackaudio.org/downloads/ is down. It gives error 404.

**Comment by tresf** [comment]
> The download link for windows users at http://jackaudio.org/downloads/ is down. It gives error 404.

Seems to be working now.  The only broken link is the tarball which points to dropbox.  Should instead be changed to https://github.com/jackaudio/jack2/archive/v1.9.10.tar.gz.

**Comment by falkTX** [comment]
has been fixed a while ago, closing
