### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by yurivict** [jackaudio/jack1#66]
Last release was in September 2016.

**Comment by falkTX** [comment]
Exactly, last release was less than a year ago.
This trend of always updating software needs to stop.

If you have a *real* reason for why jack1 needs a new release, I'm all ears.
A one year old software is not obsolete.

**Comment by yurivict** [comment]
Yes. 7 months ago I submitted a patch that enabled real-time priority mode on FreeBSD that was impossible before. Now I find that this patch is still not in a release. So I had to roll the FreeBSD port to the current github revision just to get that patch in. 7 months is simply too long.

**Comment by falkTX** [comment]
ok, then please mention that next time instead of just saying when the last release was.
let's do it like this, see if you can fix #67, then I'll handle the needed things for a release.

**Comment by yurivict** [comment]
@falkTX I am closing this for now. I would like to fix few more things. You are right, no need to rush with the release. pthread thread priority warning on FreeBSD. Maybe I can find a midi card and implement midi in OSS driver.

I would appreciate if you merge several pull requests that I submitted.

Thank you!
