### ISSUE TITLE
configure's use of mmacosx-version-min breaks compile on Mojave

### ISSUE THREAD

**Issue by DomT4** [jackaudio/jack1#81]
[configure sets](https://github.com/jackaudio/jack1/blob/cb654ada4ecfd6a95b9fb648ebd33c5af462d380/configure.ac#L332-L335) `-mmacosx-version-min=10.4` which results in `jack` attempting to link against `-lgcc_s.10.4` during compile.

Both `libgcc_s.10.4.dylib` and `libgcc_s.10.5.dylib` were removed in macOS 10.14, so the build fails like this:

```
ld: library not found for -lgcc_s.10.4
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libjack.la] Error 1
make: *** [install-recursive] Error 1
```

`-mmacosx-version-min=10.6` seems to be the absolute minimum if you intend to support macOS Mojave & want to keep it hardcoded, but another option could be to respect `MACOSX_DEPLOYMENT_TARGET` and only default to 10.6 (or newer) if that isn't set.

**Comment by falkTX** [comment]
thanks for the information.
I dont have such new system myself, or want to update to it.
PR welcome.

**Comment by DomT4** [comment]
Apologies for the delay! Filed https://github.com/jackaudio/jack1/pull/82.
