### ISSUE TITLE
Is it necessary to include the Jack framework in my project?

### ISSUE THREAD

**Issue by thinium** [jackaudio/jack1#96]
Hi, 

For my app I need to use Jack similar to what is shown in the [Simple Client](https://github.com/jackaudio/example-clients/blob/7fa089095c81e81dacd2554ae3184acc7f2d58ed/simple_client.c) example. I noticed that the example uses the Jack framework installed in the system folder (**/usr/local/include** in my OSX system). Is it safe to assume that all users will have the framework installed in the same location? Or is it necessary to add the jack framework into my project? As I can't find the pre-built library/framework in the repo, it seems that I'll need to build it manually?

Thanks in advance!

**Comment by falkTX** [comment]
you cannot add jack into your project, as users might have a different version installed and it will fail to talk with the jack server side.
the location can change, but that is up to the system to find it. when building/compiling, the linker will just set libjack.dylib symbols. and then at runtime the OS finds the library and matches function name symbols. (or something like this)
