### ISSUE TITLE
Possible to get Jack2 to follow changes in bitrate from source?

### ISSUE THREAD

**Issue by kiwi-ed** [jackaudio/jack1#99]
Hi,

I have cross-compiled and am running Jack2 on a headless ARM server ( not RPI nor off the shelf product ) and I'm experimenting with MPD connectivity. Directly connecting to ALSA within the MPD's conf will enable me to play any sample rate at it's proper rate i.e no re-sampling to 48000. However connecting to Jack2 I've noticed whatever the sample rate of the song is it's always re-sampled to 48000. Is it possible for Jack2 to follow the actual sample rate offered by MPD ie 96K/24bit to be passed to my DAC changing on a per song basis? No matter what I test everything gets re-sampled to 48000 using Jack2.

Thanks.

**Comment by falkTX** [comment]
That is not how jack works. the jack server sets up the sample rate at the start, and this cannot change while the server is running.
jack does not adapt to applications, applications must adapt to jack.
